spring:
  cors:
    allowed-origins:
      - "http://localhost:4200"  # Frontend origin
      - "http://localhost:9999"  # Gateway origin
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed-headers:
      - "*"
    allow-credentials: true
    max-age: 3600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException


management:
  endpoints:
    web:
      exposure:
        include: '*'

