spring:
  cors:
    allowed-origins:
      - "http://localhost:4200"  # Frontend origin
      - "http://localhost:9999"  # Gateway origin
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed-headers:
      - "*"
    allow-credentials: true
    max-age: 3600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
